//DisplayonConsole is class with public keyword

public class DisplayonConsole
{

//displayMSG is a function/method to execute actual business logic
public void displayMSG()
{

//System.debug is used for to display some data on console
System.debug('Hellow World');
}
}

/*
DisplayonConsole :  is a class
dc : is a instance variable
new : is a keyword
DisplayonConsole(); : class instantiation with constructor

DisplayonConsole dc=new DisplayonConsole();   
dc.displayMSG();

Developer console : to execute this class
Debug > Open Anonymous window
*/